INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo1@gmail.com', 'Nicolas', 'Alvarez', 'direccion 1', '098776554', 'password1');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo2@gmail.com', 'Rodrigo', 'Gimenez', 'direccion2', '267482', 'password2');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo3@gmail.com', 'Pablo ', 'Gimenez', 'direccion 2', '098098098', 'password3');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo4@gmail.com', 'ana maria', 'libertad', 'direcc generica', '457', 'password4');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo5@gmail.com', 'emilia ', 'de guzman', 'direccion salto al fondo', '25443', 'password5');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo6@gmail.com', 'clara', 'hiliarse', 'Al fondo que hay lugar', '45988864', 'password6');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo7@seguridadcorporal.com', 'patricia', 'gutierrez', 'direccion otra', '2334513', 'password7');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo8@seguridadcorporal.com', 'lucas', 'rodriguez', '18 de julio 2377', '22334455', 'password8');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo9@seguridadcorporal.com', 'esteban ', 'quito', 'no me acuerdo', '09828848', 'password9');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('correo10@seguridadcorporal.com', 'maximilian', 'fija', 'rio negro entre j carlos rodriguez y marcelino gutierrez', '56778883', 'password10');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('Lcarambula@seguridadcorporal.com', 'Leonardo', 'Carambula', 'Programacion Web', '22114433', 'lcarambula');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('Lacuna@seguridadcorporal.com', 'Laura', 'Acuna', 'Diseño Web', '098465773 098887766', 'lacuna');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('Cbarrios@seguridadcorporal.com', 'Christian', 'Barrios', 'Sist Ope y Gest de Proy', '098098098', 'cbarrios');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('Agonzalez@seguridadcorporal.com', 'Ana', 'Gonzalez', 'ADA', '123123321', 'agonzalez');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('Nhernandez@seguridadcorporal.com', 'Nora', 'Hernandez', 'UTU', '123123123', 'nhernandez');
INSERT INTO `bindev`.`user` (`email`, `name`, `surname`, `address`, `phone`, `password`) VALUES ('Bgates@seguridadcorporal.com', 'Bill', 'Gates', 'Estados Unidos', '1234567890000', 'bgates');
INSERT INTO `bindev`.`role` (`name_role`, `description`) VALUES ('VENDEDOR', 'EL VENDEDOR');
INSERT INTO `bindev`.`role` (`name_role`, `description`) VALUES ('COMPRADOR', 'EL COMPRADOR');
INSERT INTO `bindev`.`role` (`name_role`, `description`) VALUES ('JEFE', 'EL JEFE');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Remera roja', 'Foto de una remera');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Remera azul', 'Foto de una remera');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Remera verde', 'Foto de una remera');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Remera amarilla', 'Foto de una remera');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Remera bordo', 'Foto de una remera');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Remera rosa', 'Foto de una remera');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Remera blanca', 'Foto de una remera');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Remera negra', 'Foto de una remera');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Categoria REMERAS', 'Foto de categoria');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Categoria BUZOS', 'Foto de categoria');
INSERT INTO `bindev`.`photos` (`name`, `description`) VALUES ('Categoria PANTALON', 'Foto de categoria');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('1', 'REMERAS', 'LAS MEJORES REMERAS','919');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('2', 'BUZOS', 'LOS MEJORES BUZOS','919');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('3', 'CHALECOS', 'LOS MEJORES CHALECOS','919');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('4', 'PANTALONES', 'LOS MEJORES PANTALONES','919');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('5', 'CASCOS ', 'LOS MEJORES CASCOS','');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('6', 'GUANTES', 'LOS MEJORES GUANTES','919');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('7', 'ZAPATOS', 'LOS MEJORES ZAPATOS','');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('8', 'LENTES', 'LOS MEJORES LENTES DE PROTECCION','919');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('9', 'GENERICA', 'CATEGORIA GENERICA','921');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('1000', 'PROMO BASICA', 'PROMO GENERICA','921');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('1001', 'PROMO PYME', 'PROMO PARA PEQUEÑAS EMPRESAS','');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('1002', 'PROMO MEDIUM', 'PROMO PARA EMPRESAS RECONOCIDAS','921');
INSERT INTO `bindev`.`category` (`id_category`, `name`, `description`, `picture`) VALUES ('1003', 'BIG PROMO', 'PROMO PARA EMPRESAS LIDERES','');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('1', 'XS', 'extra small');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('2', 'S', 'small');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('3', 'M', 'medium');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('4', 'L', 'large');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('5', 'XL', 'extra large');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('6', 'XXL', 'exXtra large');
INSERT INTO `bindev`.`SIZE` (`id_size`, `name`, `description`) VALUES ('7', 'CHICO', 'ALGO CHICO');
INSERT INTO `bindev`.`SIZE` (`id_size`, `name`, `description`) VALUES ('8', 'MEDIO', 'ALGO MEDIO');
INSERT INTO `bindev`.`SIZE` (`id_size`, `name`, `description`) VALUES ('9', 'GRANDE', 'ALGO GRANDE');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('38', 'TALLE 38', 'CALZADO 38');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('39', 'TALLE 39', 'CALZADO 39');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('40', 'TALLE 40', 'CALZADO40');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('41', 'TALLE 41', 'CALZADO TALLE 41');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('42', 'TALLE 42', 'CALZADO TALLE 42');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('43', 'TALLE 43', 'CLAZADO TALLE 43');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('44', 'TALLE 44', 'CALZADO TALLE 44');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('45', 'TALLE 45', 'CALZADO 45');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('1000', 'PROMO BASIC ', 'PROMO BASICAS');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('1001', 'PROMO PYMES', 'PROMO PEQUEÑAS EMPRESAS');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('1002', 'PROMO MEDIUM', 'PROMO PARA EMPRESAS EN GRAL');
INSERT INTO `bindev`.`size` (`id_size`, `name`, `description`) VALUES ('1003', 'PROMO BIG ', 'PROMO PARA GRANDES EMPRESAS');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('BLANCO', 'COLOR BLANCO');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('NEGRO', 'COLOR NEGRO');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('GRIS', 'COLOR GRIS');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('VERDE', 'COLOR VERDE');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('AMARILLO', 'COLOR AMARILLO');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('ANARANJADO', 'COLOR ANARANJADO');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('ROJO', 'COLOR ROJO');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('GENERICO', 'CATEGORIA COLOR GENERICA');
INSERT INTO `bindev`.`design` (`name`, `description`) VALUES ('PROMO', 'PROMO');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('1000', 'PROMO CUIDADOS', '1000', '1000', '1000', '2', '700', 'PROMO DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('1001', 'PROMO MANOS A LA OBRA', '1000', '1000', '1000', '10', '750', 'RPOMO DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('1002', 'PROMO PYMES', '1001', '1000', '1001', '10', '1000', 'PROMO DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('1003', 'PROMOS PARA TODOS', '1002', '1000', '1002', '0', '1500', 'PROMO DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('1004', 'BIG PROMO BIG', '1003', '1000', '1003', '1', '3000', 'BIG PROMO DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('2000', 'REMERA CLASICA TALLE S COLOR ROJO', '1', '6', '2', '200', '380', 'REMERA DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('2000', 'REMERA CLASICA TALLE M COLOR ROJO', '1', '6', '3', '99', '380', 'REMERA DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('2000', 'REMERA CLASICA TALLE L COLOR ROJO', '1', '6', '4', '100', '380', 'REMERA DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('2000', 'REMERA CLASICA TALLE S COLOR NEGRA', '1', '1', '2', '101', '380', 'REMERA DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('2000', 'REMERA CLASICA TALLE M COLOR NEGRA', '1', '1', '3', '0', '380', 'REMERA DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('2000', 'REMERA CLASICA TALLE XL COLOR BLANCA', '1', '0', '5', '5', '380', 'REMERA DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('2001', 'REMERA PREMIUM TALLE S COLOR ROJO', '1', '6', '2', '300', '450', 'LA MEJOR REMERA DEL MERCADO');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('3000', 'PANTALON CLASICO TALLE S COLOR GRIS', '4', '2', '2', '20', '1200', 'PANTALONES DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('3000', 'PANTALON CLASICO TALLE M COLOR GRIS', '4', '2', '3', '70', '1200', 'PANTALONES DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('3000', 'PANTALON CLASICO TALLE L COLOR GRIS', '4', '2', '4', '71', '1200', 'PANTALONES DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('4000', 'ZAPATOS TALLE 39', '7', '7', '39', '21', '3000', 'ZAPATOS DE CONSTRUCCION DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('4000', 'ZAPATOS TALLE 40', '7', '7', '40', '0', '3000', 'ZAPATOS DE CONSTRUCCION DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('4000', 'ZAPATOS TALLE 41', '7', '7', '41', '23', '3000', 'ZAPATOS DE CONSTRUCCION DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('4001', 'ZAPATOS TALLE 44', '7', '7', '44', '46', '3000', 'ZAPATOS DE CONSTRUCCION DE CALIDAD');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('5000', 'CASCO GRANDE', '5', '4', '9', '120', '1000', 'LA MEJORES CASCOS DEL MERCADO');
INSERT INTO `bindev`.`PRODUCT` (`id_product`, `name`, `product_category`, `product_design`, `product_size`, `stock`, `price`, `description`) VALUES ('5000', 'CASCO CHICO', '5', '4', '7', '150', '1000', 'LA MEJORES CASCOS DEL MERCADO');
INSERT INTO `bindev`.`delivery_time` (`id_delivery`, `name`, `description`) VALUES ('1', 'Matutino', 'L a V De 8 a 11 AM');
INSERT INTO `bindev`.`delivery_time` (`id_delivery`, `name`, `description`) VALUES ('2', 'Medio Dia', 'L a V De 13 a 16 HS');
INSERT INTO `bindev`.`delivery_time` (`id_delivery`, `name`, `description`) VALUES ('3', 'Tarde', 'L a V De 17 a 20 HS');
INSERT INTO `bindev`.`delivery_time` (`id_delivery`, `name`, `description`) VALUES ('4', 'Finde', 'Sabados de 8 a 13 hs');
INSERT INTO `bindev`.`delivery_time` (`id_delivery`, `name`, `description`) VALUES ('5', 'Pick-UP', 'Levanta en local');
INSERT INTO `bindev`.`supplier` (`rut`, `company_name`, `address`, `phone` ) VALUES ('211223224223','MONTEVIDEO UNIFORMES','18 DE JULIO 123','098098098');
INSERT INTO `bindev`.`supplier` (`rut`, `company_name`, `address`, `phone` ) VALUES ('212234522467','FUPI','WWW.FUPI.COM','240588667');
INSERT INTO `bindev`.`supplier` (`rut`, `company_name`, `address`, `phone` ) VALUES ('211222344412','VICAS','WWW.VICAS.COM.UY','EL NUM DE CARLOS 22334455');
INSERT INTO `bindev`.`supplier` (`rut`, `company_name`, `address`, `phone` ) VALUES ('222573323342','QARIMPORT','MALDONADO 123','22334455');
INSERT INTO `bindev`.`supplier` (`rut`, `company_name`, `address`, `phone` ) VALUES ('214898752423','MUNDO TRABAJO','FLORIDA - CALLE 7 AL 3440','32243344');
INSERT INTO `bindev`.`status` (`id_status`,`name`, `description`) VALUES ('1', 'PENDIENTE', 'COMPRA EN ESTADO PENDIENTE DE PAGO');
INSERT INTO `bindev`.`status` (`id_status`,`name`, `description`) VALUES ('2', 'CONFIRMADO', 'COMPRA EN ESTADO CONFIRMADO DE PAGO');
INSERT INTO `bindev`.`status` (`id_status`,`name`, `description`) VALUES ('3', 'EN VIAJE', 'COMPRA EN ESTADO EN VIAJE A DESTINO');
INSERT INTO `bindev`.`status` (`id_status`,`name`, `description`) VALUES ('4', 'CONFIRMADA', 'COMPRA CONFIRMADA Y ENTREGADA AL CLIENTE');
INSERT INTO `bindev`.`status` (`id_status`,`name`, `description`) VALUES ('5', 'PICK-UP', 'COMPRA PARA LEVANTAR EN LOCAL');
INSERT INTO `bindev`.`status` (`id_status`,`name`, `description`) VALUES ('6', 'CANCELADA', 'COMPRA EN ESTADO CANCELADA');
INSERT INTO `bindev`.`employee` (`ci`, `employee_user`, `employee_role`, `state`) VALUES ('12345010', '5010', 'jefe', '1');
INSERT INTO `bindev`.`employee` (`ci`, `employee_user`, `employee_role`, `state`) VALUES ('12345011', '5011', 'comprador', '1');
INSERT INTO `bindev`.`employee` (`ci`, `employee_user`, `employee_role`, `state`) VALUES ('12345012', '5012', 'comprador', '0');
INSERT INTO `bindev`.`employee` (`ci`, `employee_user`, `employee_role`, `state`) VALUES ('12345013', '5013', 'vendedor', '1');

